server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: springcloud-feign

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

feign:
hystrix:
enabled: true


