server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #注册中心地址,${eureka.instance.hostname}对应上面的localhost,            ${server.port}对应8080端口号
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
spring:
  application:
    #服务名称
    name: eurka-server
