server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: provide-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    first:
      initial-size: 1
      max-active: 5
    password: root
    url: jdbc:mysql://localhost:3306/spring1?characterEncoding=utf-8
    username: root
  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
